version: '3.7'
services:
  bff:
    build:
      context: 'bff/'
    environment:
      PIDFILE: /tmp/server.pid
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_ENV: 'production'
      SECRET_KEY_BASE: 'DUMMY_SECRET_KEY_BASE_FOR_BFF'
    ports:
      - 3000:3000
  main:
    build:
      context: 'main/'
    environment:
      DATABASE_URL: 'mysql2://root:password@mysql/main?encoding=utf8mb4&collation=utf8mb4_bin'
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_ENV: 'production'
      SECRET_KEY_BASE: 'DUMMY_SECRET_KEY_BASE_FOR_MAIN'
  tsukurepo_backend:
    build:
      context: 'tsukurepo_backend/'
    environment:
      DATABASE_URL: 'mysql2://root:password@mysql/tsukurepo_backend?encoding=utf8mb4&collation=utf8mb4_bin'
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_ENV: 'production'
      SECRET_KEY_BASE: 'DUMMY_SECRET_KEY_BASE_FOR_TSUKUREPO'
  mysql:
    image: mysql:5.6
    command: --slow-query-log=true --slow-query-log-file=/var/log/mysql/slow.log --long-query-time=0.1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    volumes:
      - 'mysql-data-vol:/var/lib/mysql'
volumes:
    mysql-data-vol: {}
networks:
  default:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '192.168.139.0/24'
